package com.pratap.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-15T13:00:56.655+05:30
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.pratap.com/service/Orders/", name = "Orders")
@XmlSeeAlso({com.pratap.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.pratap.com/service/Orders/ProcessOrderPlacement")
    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.pratap.com/schema/Order", partName = "orderInquiryResponse")
    public com.pratap.schema.order.OrderInquiryResponseType processOrderPlacement(

        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.pratap.com/schema/Order")
        com.pratap.schema.order.OrderInquiryType orderInquiry
    );
}
